name: 'Debug'
on:
    workflow_dispatch:
        inputs:
            feature:
                description: 'feature in src'
                required: true
                default: ''

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                baseImage:
                    - mcr.microsoft.com/devcontainers/base:ubuntu-22.04
        steps:
            - name: prepare 1000:1000
              run: |
                set -x
                cat /etc/group
                cat /etc/passwd
                id
                sudo id

            - uses: actions/checkout@v4

            - name: prepare for tests
              run: |
                bash prepare-for-tests.sh

            - name: 'Install latest devcontainer CLI'
              run: sudo npm install -g @devcontainers/cli

            - name: "Generating tests for '${{ inputs.feature }}' against '${{ matrix.baseImage }}'"
              run: |
                if [ -f "./test/${{ inputs.feature }}/test.sh" ]; then
                  sudo devcontainer features test --skip-scenarios -f ${{ inputs.feature }} -i ${{ matrix.baseImage }} -u vscode .
                fi

            - name: "Generating tests for '${{ inputs.feature }}' scenarios"
              run: |
                if [ -f "./test/${{ inputs.feature }}/scenarios.json" ]; then
                  sudo devcontainer features test -f ${{ inputs.feature }} --skip-autogenerated --skip-duplicated -u vscode .
                fi
