name: "Release Images"
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/release-images.yml"
      - "images/src/flutter/**"

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    strategy:
      matrix:
        images:
          - flutter
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image - ${{ matrix.images }}
        uses: devcontainers/ci@v0.3
        with:
          subFolder: images/src/${{ matrix.images }}
          imageName: ghcr.io/${{ github.actor }}/devcontainers-images-${{ matrix.images }}
          push: always
