name: "Test Images"
on:
    push:
        branches:
            - "master"
        paths:
            - ".github/workflows/test-images.yml"
            - "images/**"
            - "features/**/devcontainer-feature.json"
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                images:
                    - flutter
                    - go
                    - go-and-node
                    - unidbg
                    - web3-dev
                    - ultralytics
        steps:
            - name: prepare 1000:1000
              run: |
                  set -x
                  cat /etc/group
                  cat /etc/passwd
                  id
                  sudo id

            - uses: actions/checkout@v4

            - uses: rokibhasansagar/slimhub_actions@a28a11a35d81967c82448c183cb17a34b7514a9a
              with:
                  retain: "docker_buildkit,container_tools,nodejs_npm"

            - name: prepare for tests
              run: |
                  cd features
                  bash prepare-for-tests.sh

            - name: "Install latest devcontainer CLI"
              run: sudo npm install --ignore-scripts -g @devcontainers/cli

            - name: "Generating tests for '${{ matrix.images }}'"
              run: |
                  cd images/src/${{ matrix.images }}
                  sudo devcontainer build --workspace-folder . --image-name ${{ matrix.images }}
